title: Hacking Delft
email: victorkrook96@gmail.com
description: >
  Here is a blog from my adventure on exchange studies at TU Delft.
baseurl: "/"
static_url: "/assets/"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  victorhook

# Build settings
theme: minima
permalink: /:categories/:year-:month-:day/:title/

# Needed to allow todays date to show.
future: true

# Variables
nav_links:
  - name: mrhookv.com
    url: https://mrhookv.com/
    icon: "bi bi-sunglasses"
front_page_posts: 2